package cn.steve.realm;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by yantinggeng on 2016/11/4.
 */

public class User extends RealmObject {

    private String name;
    private int age;

    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    public boolean hasLongName() {
        return name.length() > 7;
    }

}
